version: '3.8'
name: resque
services:
  app:
    build:
      context: ../
      dockerfile: devops/containers/app/Dockerfile
      target: dev
    # https://github.com/QualityUnit/QuCloud/blob/master/QuSalt/salt/roots/php-resque/conf/resqu.service
    command: php scripts/startManagers.php /app-config/config.yml
    volumes:
      - ../:/app:ro
      # App config
      - ./deploy/containers/app/config/app-config:/app-config:ro
      - ./deploy/containers/app/secrets/app-secrets:/app-secrets:ro
      # PHP
      - ./deploy/containers/app/config/usr--local--etc--php--conf.d--zzz-env.ini:/usr/local/etc/php/conf.d/zzz-env.ini:ro
    environment:
      RESQU_NODE_ID: 'dev-local'
      # DEV
      PHP_IDE_CONFIG: "serverName=resque.la.localhost"
      #XDEBUG_CONFIG: "mode=debug client_host=host.docker.internal start_with_request=yes log_level=7"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      idp:
  app-prod:
    build:
      context: ../
      dockerfile: devops/containers/app/Dockerfile
      target: prod
    # https://github.com/QualityUnit/QuCloud/blob/master/QuSalt/salt/roots/php-resque/conf/resqu.service
    environment:
      RESQU_NODE_ID: 'dev-local'
    volumes:
      # App config
      - ./deploy/containers/app/config/app-config:/app-config:ro
      - ./deploy/containers/app/secrets/app-secrets:/app-secrets:ro
      # PHP
      - ./deploy/containers/app/config/usr--local--etc--php--conf.d--zzz-env.ini:/usr/local/etc/php/conf.d/zzz-env.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      idp:
  builder:
    profiles:
      - cli
    build:
      context: ../
      dockerfile: devops/containers/app/Dockerfile
      target: builder
      args:
        BUILDER_UID: ${HOST_UID:-1000}
        BUILDER_GID: ${HOST_GID:-1000}
    command: sleep infinity
    user: builder
    working_dir: /project-root
    networks:
      idp:
    volumes:
      - ../:/project-root
      - resque-builder-home:/home/builder
volumes:
  resque-builder-home:
networks:
  idp:
    name: idp
