name: Build release & deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: shivammathur/setup-php@2.25.0
        with:
          php-version: '8.1'
          coverage: none
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew dist
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./build/*.zip"